version: '1.0'
name: test
displayName: test
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
variables:
  POST_API: https://api.learningcamp.cn/web/api/courseRank/createByThird
stages:
  - name: build-test
    displayName: build-test
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@gcc
        name: build_gcc
        displayName: build
        gccVersion: '9.4'
        commands:
          - apt-get update
          - ''
          - apt-get install -y curl
          - ''
          - mkdir build
          - ''
          - make test-output
          - ''
          - make save-test-results
          - ''
          - '# 假设 GITEE_USER_NAME 环境变量包含了用户的 Gitee ID'
          - gitee_id="$GITEE_PIPELINE_TRIGGER_USER"
          - ''
          - '# 读取现有的 JSON 文件'
          - json_file="build/test_results.json"
          - existing_json=$(cat "$json_file")
          - ''
          - '# 使用 jq 工具来更新 JSON 文件中的 giteeName 字段'
          - updated_json=$(echo "$existing_json" | jq --arg gitee_id "$gitee_id" '.name = $gitee_id')
          - ''
          - '# 将更新后的 JSON 写回文件'
          - echo "$updated_json" > "$json_file"
          - ''
          - cat build/test_results.json
          - ''
          - 'curl -X POST "$POST_API" -H "accept: application/json;charset=utf-8" -H "Content-Type: application/json" -d "$(cat build/test_results.json)" -v'
          - ''
          - ''
        artifacts:
          - name: test_results
            path:
              - ./build/test_results.json
        caches: []
        notify: []
        strategy:
          retry: '0'
